FROM python:3.11-slim

RUN pip install --no-cache-dir \
    jax \
    jaxlib \
    flax \
    optax \
    matplotlib \
    numpy \
    pandas \
    datasets \
    transformers

WORKDIR /app

ENTRYPOINT ["python"]
